import {ARCHETYPES,fieldCard,poweredNodes,reachableSocket,createBattle,advance,STATUS_NAMES} from './game.js';
import {createRun,availableNodes,selectNode,encounterFor,resolveVictory,chooseReward,skipReward,buyCard,leaveShop,leaveCampfire} from './run.js';
import {MUSIC_CONFIG,chordForBeat,allocateChordVoices} from './cards.js';
function renderLoadout(targetId){const target=$(targetId);if(!run||!target)return;const used=new Set(run.board.filter(Boolean).map(card=>card.id)),powered=poweredNodes(run.board),bench=run.collection.filter(card=>!used.has(card.id));target.innerHTML=`<h3>Current loadout</h3><div class="loadout-columns"><div><h4>Board</h4><div class="grid compact loadout-grid">${run.board.map((node,index)=>`<div class="cell ${node&&!powered.has(index)?'dormant':''}">${card(node,index)}</div>`).join('')}</div></div><div><h4>Bench · ${bench.length}</h4><div class="bench-list">${bench.map(item=>`<div class="tile-card">${card(item)}</div>`).join('')||'<p>All cards fielded.</p>'}</div></div></div>`}
function fastForward(){if(!battle||battle.over)return;clearInterval(timer);timer=null;let safety=0;while(!battle.over&&safety++<1000)battle=advance(battle);renderBattle();tick();if(!battle.over)timer=setInterval(tick,850)}
let selectedCardId=null;
let buildInputsBound=false,pointerCardId=null,pointerBoardIndex=null,pointerTile=null;
function bindBuildInputs(){if(buildInputsBound)return;buildInputsBound=true;const inventory=$('tile-inventory'),grid=$('player-grid');inventory.addEventListener('pointerdown',event=>{const tile=event.target.closest('[data-tile]');if(!tile||event.button!==0)return;event.preventDefault();pointerCardId=tile.dataset.tile;pointerTile=tile;tile.classList.add('dragging')});grid.addEventListener('pointerdown',event=>{if(event.target.closest('[data-remove]'))return;const tile=event.target.closest('[data-board-tile]');if(!tile||event.button!==0)return;event.preventDefault();pointerBoardIndex=+tile.dataset.boardTile;pointerTile=tile;tile.classList.add('dragging')});document.addEventListener('pointerup',event=>{if(!pointerCardId&&pointerBoardIndex===null)return;const target=document.elementFromPoint(event.clientX,event.clientY),cell=target?.closest('[data-cell]');const cardId=pointerCardId,boardIndex=pointerBoardIndex;pointerTile?.classList.remove('dragging');pointerCardId=null;pointerBoardIndex=null;pointerTile=null;if(cardId){if(cell)place(cardId,+cell.dataset.cell);else{selectedCardId=cardId;renderBuild()}}else if(!cell){run.board[boardIndex]=null;renderBuild()}else if(+cell.dataset.cell!==boardIndex){const targetIndex=+cell.dataset.cell;[run.board[boardIndex],run.board[targetIndex]]=[run.board[targetIndex],run.board[boardIndex]];renderBuild()}});inventory.addEventListener('dragstart',event=>event.preventDefault());inventory.addEventListener('click',event=>{const tile=event.target.closest('[data-tile]');if(!tile)return;selectedCardId=tile.dataset.tile;renderBuild()});grid.addEventListener('click',event=>{const cell=event.target.closest('[data-cell]');if(cell&&selectedCardId)place(selectedCardId,+cell.dataset.cell)})}
let run,encounter,enemyPreview,battle,battleStartRun,timer,intermissionTimer,muted=false,musicPaused=false,dragged,musicVolume=3.5;const $=id=>document.getElementById(id),views=['start-view','map-view','campfire-view','shop-view','setup-view','battle-view','reward-view','end-view'],dirs={N:'↑',E:'→',S:'↓',W:'←'},inside={N:'↓',E:'←',S:'↑',W:'→'};
function installBoardShiftControls(){const grid=$('player-grid'),wrap=document.createElement('div');wrap.className='board-grid-controls';wrap.innerHTML='<button type="button" class="board-shift board-shift-n" data-shift="N" aria-label="Move board up">↑</button><button type="button" class="board-shift board-shift-e" data-shift="E" aria-label="Move board right">→</button><button type="button" class="board-shift board-shift-s" data-shift="S" aria-label="Move board down">↓</button><button type="button" class="board-shift board-shift-w" data-shift="W" aria-label="Move board left">←</button>';grid.replaceWith(wrap);wrap.append(grid)}
function installMusicPauseControl(){const button=document.createElement('button');button.id='pause-music-button';button.type='button';$('mute-button').insertAdjacentElement('afterend',button);button.onclick=()=>{if(button.disabled)return;musicPaused=!musicPaused;if(musicPaused)stopDrone();else startDrone();updateMusicControls()};updateMusicControls()}
function updateMusicControls(){const button=$('pause-music-button');if(!button)return;button.disabled=Boolean(battle&&!battle.over);button.textContent=musicPaused?'Resume music':'Pause music'}
function canShiftBoard(direction){if(!run?.board?.some(Boolean))return false;return run.board.every((card,index)=>!card||(direction==='N'?index>=5:direction==='S'?index<20:direction==='W'?index%5>0:index%5<4))}
function shiftBoard(direction){if(!canShiftBoard(direction))return;const delta={N:-5,E:1,S:5,W:-1}[direction],next=Array(25).fill(null);run.board.forEach((card,index)=>{if(card)next[index+delta]=card});run.board=next;renderBuild()}
installBoardShiftControls();
installMusicPauseControl();
function show(id){bindBuildInputs();$('fast-button').onclick=fastForward;views.forEach(v=>$(v).hidden=v!==id);$('run-hud').hidden=!run;if(run)$('run-hud').innerHTML=`<b>${ARCHETYPES[run.archetype].name}</b><span>HP ${run.hp}/${run.maxHp}</span><span>Gold ${run.gold}</span><span>Wins ${run.wins}</span>`;if(id==='shop-view')queueMicrotask(()=>renderLoadout('shop-loadout'));if(id==='reward-view')queueMicrotask(()=>renderLoadout('reward-loadout'))}
function mechanicTooltip(n){const value=n.type==='activator'?n.params?.cadence||4:n.type==='delay'?n.params?.beats||2:n.params?.threshold||3;return n.type==='activator'?`Activator: creates one pulse every ${value} beats.`:n.type==='delay'?`Delay: holds each incoming pulse for ${value} beats, then releases it.`:n.type==='accumulator'?`Accumulator: stores incoming pulses and releases one after ${value} charges.`:n.type==='switcher'?'Switcher: sends each pulse down one output, alternating outputs in order.':n.type.startsWith('multi')?`Multi ×${n.type.slice(-1)}: activates only when ${n.type.slice(-1)} pulses arrive on the same beat.`:''}
const STATUS_TOOLTIPS={poison:'Poison: deals its stacks as unblockable damage each beat, then loses 1 stack.',strong:'Strong: adds its stacks to attack damage.',weak:'Weak: subtracts its stacks from attack damage.',vulnerable:'Vulnerable: takes extra attack damage equal to its stacks.',dextrous:'Dextrous: adds its stacks to block gained.',brittle:'Brittle: subtracts its stacks from block gained.',stunned:'Stunned: each stack cancels an activation, but its pulse still continues.'};
function statusTooltips(n){const effects=[...(n.action?.effects||[]),...(n.action?.rules?.onCooldown||[]),...(n.action?.reactive||[])],statuses=[...new Set(effects.filter(effect=>effect.type==='status').map(effect=>effect.status))];return statuses.map(status=>STATUS_TOOLTIPS[status]).filter(Boolean)}
function card(n,i,edit,meter){if(!n)return '';const rhythm=n.type==='relay'||n.type==='relayTurn'?'':n.type==='activator'?`ACTIVATOR ${n.params?.cadence||4}`:n.type==='delay'?`DELAY ${n.params?.beats||2}`:n.type==='accumulator'?`ACCUMULATOR ${n.params?.threshold||3}`:n.type==='switcher'?'SWITCHER':`MULTI ${n.type.slice(-1)}`,tooltip=[mechanicTooltip(n),...statusTooltips(n)].filter(Boolean).join(' '),tooltipAttr=tooltip?` data-tooltip="${tooltip}" aria-label="${tooltip}"`:'',drag=edit?` draggable data-board-tile="${i}"`:'',ports=[...n.in,...n.out],portClearance=`${ports.includes('W')?' has-west-port':''}${ports.includes('E')?' has-east-port':''}`,degree=Math.max(0,n.degree||0)%5;let m='';const runtime=meter?.side.nodeState[i],pulseCount=meter?.side.activePulseCounts?.[i]||0;if(meter&&n.type==='activator'){const cadence=n.params?.cadence||4,v=((meter.beat-1)%cadence)+1;m=`<span class="charge-meter"><i style="width:${v/cadence*100}%"></i><b>${v}/${cadence}</b></span>`}if(meter&&n.type==='accumulator'){const charge=meter.side.charges[i],v=charge?.count||0,threshold=n.params?.threshold||3;m=`<span class="charge-meter accumulator-meter"><i style="width:${v/threshold*100}%"></i><b>${v}/${threshold}</b></span>`}if(meter&&n.type==='delay'&&meter.side.delays[i]){const v=meter.side.delays[i].due-meter.beat;m=`<span class="charge-meter delay-meter"><i style="width:${v/(n.params?.beats||2)*100}%"></i><b>${v} TO GO</b></span>`}if(meter&&runtime?.exhausted)m='<span class="node-state exhausted">EXHAUSTED</span>';else if(meter&&runtime?.readyAt>meter.beat)m=`<span class="node-state cooldown">COOLDOWN ${runtime.readyAt-meter.beat}</span>`;else if(meter&&n.type==='switcher')m=`<span class="node-state switcher-state">NEXT ${dirs[n.out[(runtime?.switchIndex||0)%n.out.length]]}</span>`;const pulseState=pulseCount>1?`<span class="node-state pulse-intensity">${n.type.startsWith('multi')?'SYNC':'PULSE'} ×${pulseCount}</span>`:'';return `<div class="node ${n.type}${portClearance}"${tooltipAttr}${drag}>${n.in.map(d=>`<span class="port in ${d.toLowerCase()}">${inside[d]}</span>`).join('')}${n.out.map(d=>`<span class="port out ${d.toLowerCase()}">${dirs[d]}</span>`).join('')}<span class="degree-dot degree-${degree}" title="Scale degree ${degree+1}" aria-label="Scale degree ${degree+1}"></span><span class="card-action">${n.action.name}</span><span class="node-name">${rhythm}</span>${edit?`<button class="remove-tile" data-remove="${i}">×</button>`:''}<span class="action-copy">${n.action.text}</span>${m}${pulseState}</div>`}
function renderMap(){show('map-view');const available=new Set(availableNodes(run).map(n=>n.id));$('map-message').textContent='Fights earn gold and cards. Bosses are mandatory checkpoints with major rewards.';$('map-grid').innerHTML=run.map.map(row=>`<div class="map-row ${row[0]?.kind==='boss'?'boss-row':''}">${row.map(n=>`<button data-map="${n.id}" class="map-node ${n.kind} ${available.has(n.id)?'available':''} ${n.visited?'visited':''}" ${available.has(n.id)?'':'disabled'}><b>${n.kind==='fight'?'⚔':n.kind==='miniboss'?'☠':n.kind==='boss'?'♛':n.kind==='campfire'?'♨':'$'}</b><span>${n.kind}</span></button>`).join('')}</div>`).join('');document.querySelectorAll('[data-map]').forEach(e=>e.onclick=()=>enter(e.dataset.map))}
function enter(id){run=selectNode(run,id);if(run.phase==='campfire'){show('campfire-view');$('campfire-copy').textContent=`You recover 30% of maximum HP. Current HP: ${run.hp}/${run.maxHp}.`}else if(run.phase==='shop')shop();else build()}
function shop(){show('shop-view');$('shop-offers').innerHTML=run.offers.map(c=>`<article class="offer-card">${card(c)}<button data-buy="${c.id}" ${run.gold<25?'disabled':''}>Buy · 25 gold</button></article>`).join('')||'<p>Sold out.</p>';document.querySelectorAll('[data-buy]').forEach(e=>e.onclick=()=>{run=buyCard(run,e.dataset.buy);shop()})}
function build(){encounter=encounterFor(run);enemyPreview=createBattle([],encounter.enemy,encounter.scale,{enemyHp:encounter.enemyHp,enemyStrength:encounter.enemyStrength,enemyPieces:encounter.enemyPieces,enemyDepth:encounter.enemyDepth,enemyRank:encounter.enemyRank,bossId:encounter.bossId,seed:encounter.seed}).enemy.board;$('archetype-label').textContent=ARCHETYPES[run.archetype].name;$('enemy-label').textContent=`${encounter.boss?encounter.bossName:ARCHETYPES[encounter.enemy].name}${encounter.miniboss?' MINIBOSS':encounter.boss?' BOSS':''}`;$('archetype-copy').textContent=encounter.boss?'Boss: its Reprisal reaches you on beat 20. Victory: +30 gold and five cards.':encounter.miniboss?'Miniboss: +50% HP.':'Victory: +10 gold and one card.';show('setup-view');renderBuild()}
function renderBuild(){const used=new Set(run.board.filter(Boolean).map(x=>x.id)),p=poweredNodes(run.board),ep=poweredNodes(enemyPreview);$('tile-inventory').innerHTML=run.collection.filter(c=>!used.has(c.id)).map(c=>`<div class="tile-card" draggable data-tile="${c.id}">${card(c)}</div>`).join('')||'<p>All cards fielded.</p>';$('player-grid').innerHTML=run.board.map((n,i)=>`<div class="cell ${n&&!p.has(i)?'dormant':''}" data-cell="${i}">${card(n,i,true)}</div>`).join('');$('enemy-preview-grid').innerHTML=enemyPreview.map((n,i)=>`<div class="cell ${n&&!ep.has(i)?'dormant':''}">${card(n,i)}</div>`).join('');const ok=reachableSocket(run.board);$('validation').textContent=ok?'Ready to battle.':'Place a connected activator card.';$('start-button').disabled=!ok;document.querySelectorAll('[data-shift]').forEach(button=>{const direction=button.dataset.shift;button.disabled=!canShiftBoard(direction);button.onclick=()=>shiftBoard(direction)});wire()}
function payload(event){if(dragged)return dragged;try{return JSON.parse(event.dataTransfer.getData('application/x-loopdeck-card')||'null')}catch{return null}}
function place(cardId,index){const c=run.collection.find(x=>x.id===cardId);if(c&&!run.board[index]){run.board[index]=fieldCard(c);selectedCardId=null;renderBuild()}}
function wire(){document.querySelectorAll('[data-tile],[data-board-tile]').forEach(e=>{e.ondragstart=event=>{dragged=e.dataset.boardTile!==undefined?{placed:+e.dataset.boardTile}:{id:e.dataset.tile};event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('application/x-loopdeck-card',JSON.stringify(dragged))};e.ondragend=()=>{dragged=null};if(e.dataset.tile)e.onclick=()=>{selectedCardId=e.dataset.tile;renderBuild()}});const deal=$('tile-inventory');deal.ondragover=e=>{if(payload(e)?.placed!==undefined)e.preventDefault()};deal.ondrop=e=>{e.preventDefault();const item=payload(e);if(item?.placed!==undefined){run.board[item.placed]=null;selectedCardId=null;renderBuild()}};document.querySelectorAll('[data-cell]').forEach(e=>{e.ondragover=x=>{x.preventDefault();x.dataTransfer.dropEffect='move'};e.ondrop=x=>{x.preventDefault();const item=payload(x),i=+e.dataset.cell;if(item?.id)place(item.id,i);else if(item?.placed!==undefined&&item.placed!==i){[run.board[item.placed],run.board[i]]=[run.board[i],run.board[item.placed]];renderBuild()}};e.onclick=()=>{if(selectedCardId)place(selectedCardId,+e.dataset.cell)}});document.querySelectorAll('[data-remove]').forEach(e=>e.onclick=event=>{event.stopPropagation();run.board[+e.dataset.remove]=null;renderBuild()})}
function start(){clearInterval(timer);stopIntermissionMusic();battleStartRun=structuredClone(run);battle=createBattle(structuredClone(run.board),encounter.enemy,encounter.scale,{playerHp:run.hp,playerMaxHp:run.maxHp,enemyHp:encounter.enemyHp,enemyStrength:encounter.enemyStrength,enemyPieces:encounter.enemyPieces,enemyDepth:encounter.enemyDepth,enemyRank:encounter.enemyRank,bossId:encounter.bossId,seed:encounter.seed});battle.soundtrack=run.soundtrack;battle.progression=run.progression;musicPaused=false;$('battle-result').hidden=true;document.querySelectorAll('#battle-view .battle-controls button').forEach(button=>button.disabled=false);$('pause-button').textContent='Pause';startDrone();updateMusicControls();show('battle-view');renderBattle();timer=setInterval(tick,850);tick()}
function renderBattle(){for(const [id,s] of [['player',battle.player],['enemy',battle.enemy]]){const p=poweredNodes(s.board),statuses=STATUS_NAMES.filter(name=>s.statuses[name]).map(name=>`${name} ${s.statuses[name]}`).join(' · ')||'No statuses';$(`${id}-stats`).innerHTML=`<h2>${s.name}</h2><div class="health"><i style="width:${s.hp/s.maxHp*100}%"></i></div><div class="statline">${s.hp}/${s.maxHp} HP · Block ${s.block}</div><div class="statusline">${statuses}</div>`;$(`battle-${id}-grid`).innerHTML=s.board.map((n,i)=>`<div class="cell ${n&&!p.has(i)?'dormant':''} ${s.activeNodes.includes(i)?'active-pulse':''} ${s.misfireNodes.includes(i)?'misfire-pulse':''} ${s.stunnedNodes.includes(i)?'stunned-pulse':''} ${s.partialNodes[i]?'partial-pulse':''}" style="--pulse-fill:${s.partialNodes[i]||0}">${card(n,i,false,{side:s,beat:battle.beat})}</div>`).join('')}$('beat-label').textContent=`BEAT ${battle.beat}`;$('event-log').innerHTML=battle.log.slice(-60).reverse().map(x=>`<li>${x}</li>`).join('')}
function soundtrack(){return MUSIC_CONFIG.soundtracks[battle?.soundtrack]||MUSIC_CONFIG.soundtracks.aeolian}
function musicBus(context){let bus=window.__loopDeckMix;if(bus?.context===context)return bus.input;const compressor=context.createDynamicsCompressor(),input=context.createGain();compressor.threshold.value=-20;compressor.knee.value=18;compressor.ratio.value=8;compressor.attack.value=.003;compressor.release.value=.18;input.gain.value=musicVolume;input.connect(compressor).connect(context.destination);window.__loopDeckMix={context,input,compressor};return input}
function stopDrone(){const drone=window.__loopDeckDrone;if(!drone)return;drone.gain.gain.cancelScheduledValues(drone.context.currentTime);drone.gain.gain.setTargetAtTime(.0001,drone.context.currentTime,.2);drone.osc.stop(drone.context.currentTime+.7);window.__loopDeckDrone=null}
function startDrone(){if(muted||musicPaused)return;try{const C=window.AudioContext||window.webkitAudioContext,c=window.__audio||(window.__audio=new C()),preset=soundtrack(),old=window.__loopDeckDrone;if(old?.preset===preset.id)return;stopDrone();const osc=c.createOscillator(),filter=c.createBiquadFilter(),gain=c.createGain(),now=c.currentTime;osc.type=preset.droneWave;osc.frequency.value=preset.tonicHz;filter.type='lowpass';filter.frequency.value=260;filter.Q.value=1.5;gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.03,now+.8);osc.connect(filter).connect(gain).connect(musicBus(c));osc.start(now);window.__loopDeckDrone={osc,gain,context:c,preset:preset.id}}catch(error){console.warn('Drone playback skipped.',error)}}
function retuneDrone(context,preset,chord,now){const drone=window.__loopDeckDrone;if(drone?.context===context&&drone.preset===preset.id)drone.osc.frequency.setTargetAtTime(preset.tonicHz*2**(chord.root/12),now,.12)}
function rageNotes(voice,chord){const activations=voice.activations,slots=Math.min(activations+1,4),layers=activations>=9?[-12,0,12]:activations>=5?[0,12]:[0],spacing=slots===1?0:.28/(slots-1);return Array.from({length:slots},(_,slot)=>layers.map(layer=>({semitones:chord.root+chord.tones[slot%chord.tones.length]+Math.floor(slot/chord.tones.length)*12+layer,at:slot*spacing,gain:.055/layers.length}))).flat()}
function playVoice(context,bus,preset,voice,at,gain=.055){const count=Math.min(voice.pulseCount||1,3),sync=voice.card?.type?.startsWith('multi')&&count>1,starts=sync?[at]:Array.from({length:count},(_,pulse)=>at+pulse*.1),intervals=sync?[0,4,7].slice(0,count):[0];for(const start of starts)for(const interval of intervals){const n=context.createOscillator(),ng=context.createGain();n.frequency.value=voice.root*2**((voice.semitones+interval)/12);n.type=voice.label==='Player'?preset.nodeWave:'triangle';ng.gain.setValueAtTime(.0001,start);ng.gain.exponentialRampToValueAtTime(gain/(count*intervals.length),start+.035);ng.gain.exponentialRampToValueAtTime(.001,start+.26);n.connect(ng).connect(bus);n.start(start);n.stop(start+.3)}}
function sound(events){if(muted||musicPaused)return;try{const C=window.AudioContext||window.webkitAudioContext,c=window.__audio||(window.__audio=new C()),now=c.currentTime,preset=soundtrack(),chord=chordForBeat(preset,battle.beat,battle.progression),bus=musicBus(c),dissonant=events.some(event=>event.includes('misfires'));retuneDrone(c,preset,chord,now);const o=c.createOscillator(),g=c.createGain(),stingDuration=dissonant?.2:.55;o.frequency.value=preset.tonicHz*2**((chord.root+(dissonant?1:0))/12);o.type=dissonant?'sawtooth':preset.nodeWave;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(dissonant?.022:(battle.beat%4===1?.08:.04),now+.04);g.gain.exponentialRampToValueAtTime(.001,now+(dissonant?.18:.52));o.connect(g).connect(bus);o.start();o.stop(now+stingDuration);const candidates=[['Player',battle.player,preset.playerRoot],['Enemy',battle.enemy,preset.enemyRoot]].flatMap(([label,side,root])=>side.activeNodes.map(index=>{const card=side.board[index];return {label,index,root,degree:Number.isInteger(card?.degree)?card.degree:0,card,activations:side.nodeState[index]?.activations||0,pulseCount:side.activePulseCounts?.[index]||1}})),rage=candidates.filter(voice=>voice.card?.action?.music?.rageMotif).slice(0,1),voices=allocateChordVoices(preset,battle.beat,candidates.filter(voice=>!voice.card?.action?.music?.rageMotif),5,battle.progression);voices.forEach((voice,i)=>playVoice(c,bus,preset,voice,now+i*.025));rage.forEach(voice=>rageNotes(voice,chord).forEach(note=>playVoice(c,bus,preset,{...voice,semitones:note.semitones},now+note.at,note.gain)))}catch(error){console.warn('Audio playback skipped for this beat.',error)}}
function playFrozenPerformance(){if(!battle?.over)return;battle=advance(battle);sound(battle.events);renderBattle()}
function startIntermissionMusic(){if(!battle?.over||intermissionTimer)return;playFrozenPerformance();intermissionTimer=setInterval(playFrozenPerformance,850)}
function stopIntermissionMusic(){clearInterval(intermissionTimer);intermissionTimer=null}
function returnToBuild(){if(!battleStartRun)return;clearInterval(timer);timer=null;stopIntermissionMusic();stopDrone();run=structuredClone(battleStartRun);battle=null;musicPaused=false;$('battle-result').hidden=true;updateMusicControls();build()}
function tick(){if(!battle||battle.over&&battle.resolved)return;battle=advance(battle);sound(battle.events);renderBattle();if(battle.over&&!battle.resolved){battle.resolved=true;clearInterval(timer);timer=null;run.hp=battle.player.hp;updateMusicControls();startIntermissionMusic();if(battle.result==='Victory'){battleStartRun=null;run=resolveVictory(run);rewards()}else{$('battle-result-kicker').textContent='RUN ENDED';$('battle-result-title').textContent=`Defeated on battle ${run.battleNumber}`;$('continue-result').textContent='Start a new run';$('battle-result').hidden=false;document.querySelectorAll('#battle-view .battle-controls button').forEach(button=>button.disabled=button.id!=='retry-battle')}}}
function rewards(){show('reward-view');$('reward-copy').textContent=`+${run.selectedNode.kind==='miniboss'?20:10} gold`; $('reward-offers').innerHTML=run.offers.map(c=>`<button class="offer-card" data-reward="${c.id}">${card(c)}</button>`).join('');document.querySelectorAll('[data-reward]').forEach(e=>e.onclick=()=>{run=chooseReward(run,e.dataset.reward);renderMap()});$('skip-reward').onclick=()=>{run=skipReward(run);renderMap()}}
function begin(id){run=createRun(id);renderMap()}$('archetype-options').innerHTML=`<button class="archetype-button" data-arch="striker"><h3>${ARCHETYPES.striker.name}</h3><p>${ARCHETYPES.striker.copy}</p></button>`;document.querySelector('[data-arch]').onclick=()=>begin('striker');$('start-button').onclick=start;$('campfire-continue').onclick=()=>{run=leaveCampfire(run);renderMap()};$('leave-shop').onclick=()=>{run=leaveShop(run);renderMap()};$('new-run').onclick=()=>{run=null;show('start-view')};$('toggle-enemy-button').onclick=()=>{const p=$('enemy-preview-panel');p.hidden=!p.hidden;$('build-layout').classList.toggle('enemy-hidden',p.hidden);$('toggle-enemy-button').textContent=p.hidden?'Show enemy':'Hide enemy'};$('pause-button').onclick=e=>{if(timer){clearInterval(timer);timer=null;e.target.textContent='Resume'}else{timer=setInterval(tick,850);e.target.textContent='Pause'}};$('step-button').onclick=()=>{clearInterval(timer);timer=null;tick()};$('retry-battle').onclick=returnToBuild;$('mute-button').onclick=()=>{muted=!muted;if(muted)stopDrone();else if(battle&&!battle.over)startDrone();$('mute-button').textContent=`Sound: ${muted?'off':'on'}`};show('start-view');
$('new-run').addEventListener('click',()=>{clearInterval(timer);timer=null;stopDrone()});
$('volume-slider').oninput=event=>{musicVolume=+event.target.value;const mix=window.__loopDeckMix;if(mix)mix.input.gain.setTargetAtTime(musicVolume,mix.context.currentTime,.03)};
$('continue-result').onclick=()=>{run=null;$('battle-result').hidden=true;show('start-view')};
$('mute-button').onclick=()=>{muted=!muted;if(muted)stopDrone();else if(!musicPaused)startDrone();$('mute-button').textContent=`Sound: ${muted?'off':'on'}`};
