export const MUSIC_CONFIG={useAuthoredCardDegrees:false,soundtracks:{aeolian:{id:'aeolian',name:'Aeolian crypt',scale:[0,2,3,5,7,8,10],voiceSlots:[0,1,2,3,4],progression:[0,5,8,7],progressionVariants:[[0,1,2,3],[1,2,3,0],[2,3,0,1]],chords:[{root:0,tones:[0,3,7]},{root:5,tones:[0,3,7]},{root:8,tones:[0,4,7]},{root:7,tones:[0,3,7]}],tonicHz:55,playerRoot:110,enemyRoot:220,nodeWave:'triangle',droneWave:'sine'},phrygian:{id:'phrygian',name:'Phrygian depths',scale:[0,1,3,5,7,8,10],voiceSlots:[0,1,2,3,4],progression:[0,8,7,0],progressionVariants:[[0,1,2,3],[1,2,3,0],[2,3,0,1]],chords:[{root:0,tones:[0,3,7]},{root:8,tones:[0,4,7]},{root:7,tones:[0,3,7]},{root:0,tones:[0,3,7]}],tonicHz:49,playerRoot:98,enemyRoot:196,nodeWave:'sine',droneWave:'triangle'},harmonicMinor:{id:'harmonicMinor',name:'Harmonic catacombs',scale:[0,2,3,5,7,8,11],voiceSlots:[0,1,2,3,4],progression:[0,5,8,7],progressionVariants:[[0,1,2,3],[1,2,3,0],[2,3,0,1]],chords:[{root:0,tones:[0,3,7]},{root:5,tones:[0,3,7]},{root:8,tones:[0,4,7]},{root:7,tones:[0,4,7]}],tonicHz:55,playerRoot:110,enemyRoot:220,nodeWave:'triangle',droneWave:'sawtooth'}}};
export function soundtrackForSeed(seed){const presets=Object.values(MUSIC_CONFIG.soundtracks);return presets[(seed>>>0)%presets.length]}
export function progressionForSeed(preset,seed){const variants=preset.progressionVariants||[[...preset.chords.keys()]];return (seed>>>0)%variants.length}
export function chordForBeat(preset,beat,progression=0){const variants=preset.progressionVariants||[[...preset.chords.keys()]],variant=variants[progression%variants.length];return preset.chords[variant[Math.floor((beat-1)/4)%variant.length]]}
export function allocateChordVoices(preset,beat,candidates,limit=5,progression=0){const chord=chordForBeat(preset,beat,progression),voices=[],heard=new Set(),slots=preset.voiceSlots||[0,1,2,3,4];for(const candidate of candidates){const degree=Math.max(0,candidate.degree||0)%slots.length,key=degree;if(heard.has(key))continue;heard.add(key);const slot=slots[degree],tone=chord.tones[slot%chord.tones.length]+12*Math.floor(slot/chord.tones.length);voices.push({...candidate,semitones:chord.root+tone});if(voices.length===limit)break}return voices}
export const PORT_WEIGHTS={connector:[.03,.42,.42,.13],low:[.18,.57,.21,.04],mid:[.42,.45,.11,.02],strong:[.72,.24,.035,.005]};
export const OFFER_CONFIG={connectorChance:.30,pulseSourceChance:.005,actionRarities:[['common',.55],['uncommon',.32],['rare',.13]]};
const amount=(base=0,from=null,per=1)=>({base,from,per}),effect=(type,target,value,extra={})=>({type,target,value,...extra}),action=(name,text,effects,tags=[],extra={})=>({name,text,effects,tags,...extra}),set=(archetype,entries)=>entries.map(entry=>({...entry,archetype,shopCost:entry.shopCost??(entry.action?25:10),rewardWeight:entry.rewardWeight??(entry.action?1:4)})),rarityByTier={low:'common',mid:'uncommon',strong:'rare'},s=(id,name,tier,node,degree,a,params={})=>({id,name,tier,offerRarity:rarityByTier[tier],node,degree,action:a,params}),d=(base,from=null,extra={})=>effect('damage','enemy',amount(base,from,extra.per??1),extra),b=(base,from=null,extra={})=>effect('block','self',amount(base,from,extra.per??1),extra),st=(target,status,base)=>effect('status',target,amount(base),{status});
const glass=(name,text,effects,tags=[])=>action(name,text,effects,tags,{modifiers:{glass:{multiplier:5,chance:.05}}});
export const CARD_DEFINITIONS=[
  ...set('*',[{id:'pulse-source',name:'Pulse Source',tier:'connector',node:'activator',params:{cadence:4,incomingChance:.1},degree:0,action:null,rewardWeight:.08},{id:'signal-link',name:'Signal Link',tier:'connector',node:'relay',degree:1,action:null},{id:'turn-link',name:'Turn Link',tier:'connector',node:'relayTurn',degree:2,action:null}]),
  ...set('striker',[
    s('strike','Strike','low','relay',0,action('Strike','Deal 6 damage',[d(6)],['attack'])),s('defend','Defend','low','relay',0,action('Defend','Gain 5 block',[b(5)],['block'])),s('twin-strike','Twin Strike','low','relayTurn',1,action('Twin Strike','Deal 4 damage twice',[d(4,null,{times:2})],['attack'])),s('iron-wave','Iron Wave','low','relayTurn',1,action('Iron Wave','Deal 5 damage. Gain 5 block',[d(5),b(5)],['attack','block'])),s('body-slam','Body Slam','strong','accumulator',3,action('Body Slam','Deal damage equal to block',[d(0,'selfBlock',{spend:'selfBlock'})],['attack']),{threshold:3}),s('pummel','Pummel','mid','multi2',2,action('Pummel','Deal 3 damage four times',[d(3,null,{times:4})],['attack'])),s('bash','Bash','low','relay',0,action('Bash','Deal 8 damage. Apply 2 vulnerable',[d(8),st('enemy','vulnerable',2)],['attack'])),s('clothesline','Clothesline','mid','delay',2,action('Clothesline','Deal 10 damage. Apply 3 weak',[d(10),st('enemy','weak',3)],['attack']),{beats:2}),
    s('anger','Anger','low','relay',1,action('Anger','Deal 3 damage plus 2 per activation',[d(3,'activationCount',{per:2})],['attack'],{music:{rageMotif:true}})),s('perfected-strike','Perfected Strike','mid','relay',1,action('Perfected Strike','Deal 6 damage plus 2 per matching card',[d(6,'matchingBoardActions',{per:2})],['attack'])),s('patient-strike','Patient Strike','mid','relay',2,action('Patient Strike','Deal 4 damage plus 3 per beat since trigger',[d(4,'beatsSinceTriggered',{per:3})],['attack'])),s('late-guard','Late Guard','mid','relay',2,action('Late Guard','Gain 3 block plus 3 per beat since pulsed',[b(3,'beatsSincePulsed',{per:3})],['block'])),s('ancient-edge','Ancient Edge','mid','delay',3,action('Ancient Edge','Deal 2 damage plus 2 per pulse age',[d(2,'pulseAge',{per:2})],['attack']),{beats:2}),s('delayed-execution','Delayed Execution','strong','accumulator',3,action('Delayed Execution','Deal 7 damage plus 3 per pulse age',[d(7,'pulseAge',{per:3})],['attack']),{threshold:3}),s('crescendo','Crescendo','mid','relay',2,action('Crescendo','Deal 5 damage plus 2 per activation',[d(5,'activationCount',{per:2})],['attack'])),s('holding-pattern','Holding Pattern','mid','delay',1,action('Holding Pattern','Gain 14 block',[b(14)],['block']),{beats:2}),s('release-valve','Release Valve','strong','accumulator',3,action('Release Valve','Deal 16 damage',[d(16)],['attack']),{threshold:3}),s('clash','Clash','strong','multi2',2,action('Clash','Deal 18 damage',[d(18)],['attack'])),s('decapitate','Decapitate','strong','multi3',3,action('Decapitate','Deal 30 damage',[d(30)],['attack'])),s('switchblade','Switchblade','mid','switcher',1,action('Switchblade','Deal 8 damage',[d(8)],['attack'])),s('alternating-guard','Alternating Guard','mid','switcher',1,action('Alternating Guard','Gain 7 block',[b(7)],['block'])),
    s('flank','Flank','mid','relay',1,action('Flank','Deal 4 damage plus 3 per connected neighbor',[d(4,'connectedNeighbors',{per:3})],['attack'])),s('isolation','Isolation','mid','relay',2,action('Isolation','Deal 7 damage plus 4 per unconnected neighbor',[d(7,'unconnectedNeighbors',{per:4})],['attack'])),s('all-in','All In','strong','multi2',3,action('All In','If all cards attack, deal 16 damage',[{...d(16),when:{type:'allBoardTag',tag:'attack'}}],['attack'])),s('bulwark-formation','Bulwark Formation','strong','multi2',3,action('Bulwark Formation','If all cards block, gain 22 block',[{...b(22),when:{type:'allBoardTag',tag:'block'}}],['block'])),s('echo-formation','Echo Formation','mid','relay',2,action('Echo Formation','Deal 4 damage plus 3 per matching card',[d(4,'matchingBoardActions',{per:3})],['attack'])),
    s('flex','Flex','low','delay',1,action('Flex','Gain 3 strong',[st('self','strong',3)],['skill']),{beats:2}),s('war-cry','War Cry','mid','relay',2,action('War Cry','Gain 4 strong. Exhaust',[st('self','strong',4)],['skill'],{rules:{exhaust:1}})),s('intimidate','Intimidate','low','relayTurn',1,action('Intimidate','Apply 3 weak',[st('enemy','weak',3)],['skill'])),s('crippling-blow','Crippling Blow','mid','accumulator',2,action('Crippling Blow','Deal 8 damage. Apply 2 weak',[d(8),st('enemy','weak',2)],['attack']),{threshold:3}),s('thunderclap','Thunderclap','mid','multi2',2,action('Thunderclap','Deal 4 damage. Apply 2 vulnerable',[d(4),st('enemy','vulnerable',2)],['attack'])),s('footwork','Footwork','low','relay',1,action('Footwork','Gain 3 dextrous',[st('self','dextrous',3)],['skill'])),s('crumbling-guard','Crumbling Guard','mid','delay',2,action('Crumbling Guard','Gain 14 block. Gain 2 brittle',[b(14),st('self','brittle',2)],['block']),{beats:2}),s('crack-armor','Crack Armor','low','relay',1,action('Crack Armor','Deal 5 damage. Apply 3 brittle',[d(5),st('enemy','brittle',3)],['attack'])),s('stagger','Stagger','mid','relay',2,action('Stagger','Deal 6 damage. Apply 2 stunned',[d(6),st('enemy','stunned',2)],['attack'])),s('bell-ringer','Bell Ringer','strong','multi2',3,action('Bell Ringer','Apply 3 stunned. Exhaust',[st('enemy','stunned',3)],['skill'],{rules:{exhaust:1}})),
    s('overguard','Overguard','strong','delay',3,action('Overguard','Gain 25 block. Cooldown 5; misfire: take 25 damage',[b(25)],['block'],{rules:{cooldown:5,onCooldown:[effect('damage','self',amount(25))]}}),{beats:2}),s('reckless-charge','Reckless Charge','strong','relayTurn',3,action('Reckless Charge','Deal 22 damage. Cooldown 4; misfire: take 10 damage',[d(22)],['attack'],{rules:{cooldown:4,onCooldown:[effect('damage','self',amount(10))]}})),s('last-stand','Last Stand','strong','multi2',3,action('Last Stand','Gain 20 block. Exhaust',[b(20)],['block'],{rules:{exhaust:1}})),s('decisive-blow','Decisive Blow','strong','multi3',3,action('Decisive Blow','Deal 26 damage. Exhaust',[d(26)],['attack'],{rules:{exhaust:1}})),s('glass-strike','Glass Strike','strong','relay',2,glass('Glass Strike','Deal 6 damage. Glass',[d(6)],['attack'])),s('glass-defend','Glass Defend','strong','relay',2,glass('Glass Defend','Gain 5 block. Glass',[b(5)],['block'])),
    s('blood-for-blood','Blood for Blood','mid','relay',2,action('Blood for Blood','Deal 5 damage plus missing HP',[d(5,'selfMissingHp')],['attack'])),s('reprisal','Reprisal','mid','relayTurn',2,action('Reprisal','Deal 4 damage plus HP lost this battle',[d(4,'selfHpLost')],['attack'])),s('no-surrender','No Surrender','mid','relay',1,action('No Surrender','Gain 4 block plus missing HP',[b(4,'selfMissingHp')],['block'])),s('finisher','Finisher','strong','accumulator',3,action('Finisher','Deal 4 damage plus enemy HP lost',[d(4,'enemyHpLost')],['attack']),{threshold:3}),s('pain-response','Pain Response','mid','relay',1,action('Pain Response','Whenever you lose HP, gain 3 block',[],['block'],{reactive:[{trigger:'damageTaken',type:'block',target:'self',value:amount(3)}]})),
    s('heavy-blade','Heavy Blade','strong','accumulator',3,action('Heavy Blade','Deal 14 damage. Strong counts three times',[d(14,null,{strongMultiplier:3})],['attack']),{threshold:3}),s('rupture-engine','Rupture Engine','strong','accumulator',3,action('Rupture Engine','Whenever you lose HP, add 1 charge',[],['skill'],{reactive:[{trigger:'damageTaken',type:'charge',target:'self',value:amount(1)}]}),{threshold:10}),s('executioner','Executioner','strong','delay',3,action('Executioner','Deal 8 damage. If enemy HP is at 25% or lower, deal 20 more',[d(8),{...d(20),when:{type:'enemyHpAtMost',fraction:.25}}],['attack']),{beats:2})
  ]),
  ...set('enemy-venom',[s('venom','Venom','low','relay',0,action('Venom','Apply 1 poison',[st('enemy','poison',1)],['debuff'])),s('toxic-slash','Toxic Slash','low','relayTurn',1,action('Toxic Slash','Deal 4 damage; apply 1 poison',[d(4),st('enemy','poison',1)],['attack'])),s('infect','Infect','mid','delay',2,action('Infect','Apply 2 poison',[st('enemy','poison',2)],['debuff']),{beats:2}),s('puncture','Puncture','strong','accumulator',3,action('Puncture','Deal 7 damage',[d(7)],['attack']),{threshold:3})])
];
export const catalogFor=archetype=>CARD_DEFINITIONS.filter(card=>card.archetype===archetype||card.archetype==='*');
export const cardById=id=>CARD_DEFINITIONS.find(card=>card.id===id);
export function outputCount(tier,random){const weights=PORT_WEIGHTS[tier],roll=random();let sum=0;for(let count=0;count<weights.length;count++){sum+=weights[count];if(roll<sum)return count}return 1}
