export const ARCHETYPES = {
  striker: { name:'Striker', copy:'Quick hits and strength build into heavy rhythm.', actions:[['Strike',6,'Deal 6 damage'],['Twin Strike',4,'Deal 4 damage twice'],['Sharpen',0,'Gain 2 strength'],['Crescendo',11,'Deal 11 damage']] },
  bulwark: { name:'Bulwark', copy:'Build a defensive wall, then turn it into impact.', actions:[['Guard',7,'Gain 7 block'],['Fortify',12,'Gain 12 block'],['Slam',0,'Spend all block; deal that much damage'],['Brace',4,'Gain 4 block and 1 strength']] },
  venom: { name:'Venom', copy:'Layer poison and let the beat do the rest.', actions:[['Venom',0,'Apply 3 poison'],['Toxic Slash',4,'Deal 4 damage; apply 2 poison'],['Infect',0,'Apply 6 poison'],['Puncture',7,'Deal 7 damage']] }
};
export const TILES = {
  relay:{name:'Relay', in:['W'],out:['E'],socket:true, detail:'Pass pulse'},
  relayTurn:{name:'Relay', in:['W'],out:['N'],socket:true, detail:'Pass pulse'},
  activator:{name:'Activator',in:['W'],out:['E','S'],socket:true,detail:'Every 4 beats'},
  delay:{name:'Delay',in:['W'],out:['E'],socket:true,detail:'Hold 2 beats'},
  accumulator:{name:'Accumulator',in:['W','N'],out:['E'],socket:true,detail:'Release after 3'},
  multi2:{name:'Multi ×2',in:['W','N'],out:['E'],socket:true,detail:'Needs 2 together'},
  multi3:{name:'Multi ×3',in:['W','N','S'],out:['E'],socket:true,detail:'Needs 3 together'}
};
const DIR={N:[-1,0],E:[0,1],S:[1,0],W:[0,-1]}, OP={N:'S',S:'N',E:'W',W:'E'};
const CLOCKWISE=['N','E','S','W'];
export function tileFor(type, turns=0){const rotate=d=>CLOCKWISE[(CLOCKWISE.indexOf(d)+turns)%4];const base=TILES[type];return {...base,type,in:base.in.map(rotate),out:base.out.map(rotate)}}
export function seeded(seed){let v=seed>>>0;return()=>((v=(v*1664525+1013904223)>>>0)/4294967296)}
export function makeEncounter(seed=Math.floor(Math.random()*0xffffffff), forcedArchetype=null) { const r=seeded(seed), keys=Object.keys(ARCHETYPES), archetype=forcedArchetype||keys[Math.floor(r()*keys.length)], multi=['multi2','multi2','multi3'][Math.floor(r()*3)], types=['activator','relay','relay','relay','relay','relayTurn','relayTurn','relayTurn','relayTurn','delay','accumulator',multi], cards=ARCHETYPES[archetype].actions; return {seed,archetype,scale:r()>.5?'major':'minor',tiles:types.sort(()=>r()-.5).map((type,i)=>{const action=type==='activator'?cards[0]:cards[Math.floor(r()*cards.length)];return {id:`t${i}`,type,turns:Math.floor(r()*4),action:{id:`t${i}-action`,name:action[0],value:action[1],text:action[2],kind:archetype}}}),enemy:keys[Math.floor(r()*keys.length)]}; }
export function emptyBoard(){return Array(25).fill(null)}
export function poweredNodes(board){const powered=new Set();board.forEach((node,i)=>{if(node?.type==='activator')powered.add(i)});let changed=true;while(changed){changed=false;board.forEach((node,i)=>{if(!node||powered.has(i)||node.type==='activator')return;let inputs=0;for(const d of node.in){const [dr,dc]=DIR[d],row=Math.floor(i/5)+dr,col=i%5+dc,j=row*5+col;if(row>=0&&row<5&&col>=0&&col<5&&powered.has(j)&&board[j]?.out.includes(OP[d]))inputs++}const required=node.type.startsWith('multi')?Number(node.type.slice(-1)):1;if(inputs>=required){powered.add(i);changed=true}})}return powered}
export function reachableSocket(board){return [...poweredNodes(board)].some(i=>board[i]?.action)}
function connect(board,index,d){const [dr,dc]=DIR[d],row=Math.floor(index/5)+dr,col=index%5+dc;if(row<0||row>4||col<0||col>4)return null;const next=row*5+col;return board[next]?.in?.includes(OP[d])?next:null}
export function createBattle(playerBoard, enemyKind, scale='minor', options={}){const enemy=enemyBoard(enemyKind,options.enemyPieces||5),playerMax=options.playerMaxHp||120,enemyHp=options.enemyHp||120;return {beat:0,scale,over:false,player:{name:'Player',hp:options.playerHp??playerMax,maxHp:playerMax,block:0,strength:0,poison:0,board:playerBoard,delays:{},charges:{},incoming:{},activeNodes:[],partialNodes:{}},enemy:{name:ARCHETYPES[enemyKind].name,hp:enemyHp,maxHp:enemyHp,block:0,strength:options.enemyStrength||0,poison:0,board:enemy,delays:{},charges:{},incoming:{},activeNodes:[],partialNodes:{}},log:[]}}
function enemyBoard(kind,pieces=5){const board=emptyBoard(), acts=ARCHETYPES[kind].actions, cards=[[0,'activator',acts[0]],[1,'relay',acts[1]],[2,'delay',acts[2]],[7,'accumulator',acts[3]],[12,'multi2',acts[0]]];cards.slice(0,pieces).forEach(([i,type,a])=>board[i]={...TILES[type],type,action:{id:`e${i}`,name:a[0],value:a[1],text:a[2],kind}});return board}
function effect(source,target,a,events){const atk=(n,label=a.name)=>{const raw=n+source.strength, absorbed=Math.min(target.block,raw);target.block-=absorbed;target.hp-=raw-absorbed;events.push(`${source.name}: ${label} deals ${raw-absorbed}${absorbed?` (${absorbed} blocked)`:''}.`)}; if(a.name==='Strike'||a.name==='Crescendo'||a.name==='Puncture')atk(a.value);else if(a.name==='Twin Strike'){atk(a.value,'Twin Strike');atk(a.value,'Twin Strike')}else if(a.name==='Sharpen'){source.strength+=2;events.push(`${source.name}: Sharpen gains 2 strength.`)}else if(a.name==='Guard'||a.name==='Fortify'||a.name==='Brace'){source.block+=a.value; if(a.name==='Brace')source.strength++;events.push(`${source.name}: ${a.name} gains ${a.value} block.`)}else if(a.name==='Slam'){const value=source.block;source.block=0;atk(value,'Slam')}else if(a.name==='Venom'||a.name==='Infect'){const n=a.name==='Venom'?3:6;target.poison+=n;events.push(`${source.name}: ${a.name} applies ${n} poison.`)}else if(a.name==='Toxic Slash'){atk(4);target.poison+=2;events.push(`${source.name}: Toxic Slash applies 2 poison.`)}}
function activate(side,other,i,events,ambient=false){const n=side.board[i];if(!n)return;side.activeNodes.push(i);events.push(`${side.name}: ${n.name} activates${!ambient&&n.action?` → ${n.action.name}`:''}.`);if(!ambient&&n.action)effect(side,other,n.action,events)}
function process(side,other,events,ambient=false){const emit=[];for(let i=0;i<25;i++){const n=side.board[i];if(!n)continue;if(n.type==='activator'&&side._beat%4===1){activate(side,other,i,events,ambient);emit.push(i)}if(side.delays[i]===side._beat){delete side.delays[i];activate(side,other,i,events,ambient);emit.push(i)}}for(const [k,count] of Object.entries(side.incoming)){const i=+k,n=side.board[i];if(!n)continue;if(n.type==='delay'){side.delays[i]=side._beat+2;events.push(`${side.name}: Delay holds a pulse.`)}else if(n.type==='accumulator'){side.charges[i]=(side.charges[i]||0)+count;if(side.charges[i]>=3){side.charges[i]-=3;activate(side,other,i,events,ambient);emit.push(i)}}else if(n.type.startsWith('multi')){const required=Number(n.type.slice(-1));if(count>=required){activate(side,other,i,events,ambient);emit.push(i)}else{side.partialNodes[i]=count/required;events.push(`${side.name}: ${n.name} receives ${count}/${required} pulses.`)}}else{activate(side,other,i,events,ambient);emit.push(i)}}side.incoming={};for(const i of emit)for(const d of side.board[i].out){const j=connect(side.board,i,d);if(j!==null)side.nextIncoming[j]=(side.nextIncoming[j]||0)+1}}
export function advance(state){const s=structuredClone(state),events=[],ambient=s.over;s.beat++;s.player._beat=s.enemy._beat=s.beat;s.player.activeNodes=[];s.enemy.activeNodes=[];s.player.partialNodes={};s.enemy.partialNodes={};s.player.nextIncoming={};s.enemy.nextIncoming={};if(!ambient)for(const side of [s.player,s.enemy])if(s.beat%3===0&&side.poison){const dmg=side.poison, absorbed=Math.min(side.block,dmg);side.block-=absorbed;side.hp-=dmg-absorbed;events.push(`${side.name}: poison deals ${dmg-absorbed}.`)}process(s.player,s.enemy,events,ambient);process(s.enemy,s.player,events,ambient);s.player.incoming=s.player.nextIncoming;s.enemy.incoming=s.enemy.nextIncoming;delete s.player.nextIncoming;delete s.enemy.nextIncoming;if(!ambient){s.player.hp=Math.max(0,s.player.hp);s.enemy.hp=Math.max(0,s.enemy.hp);s.log=[...s.log,...events];if(!s.player.hp||!s.enemy.hp){s.over=true;s.result=s.player.hp===s.enemy.hp?'Draw':s.player.hp?'Victory':'Defeat'}}return {...s,events}}
