import {cardById,catalogFor,MUSIC_CONFIG,outputCount} from './cards.js';
import {bossById} from './bosses.js';
export const ARCHETYPES={striker:{name:'Striker',copy:'Strike, defend, and build tempo with strength and vulnerability.'},'enemy-venom':{name:'Venom',copy:'Enemy-only poison pressure.'}};
export const TILES={relay:{name:'Relay',in:['W'],out:['E'],socket:true,detail:'Pass pulse'},relayTurn:{name:'Relay',in:['W'],out:['N'],socket:true,detail:'Pass pulse'},activator:{name:'Activator',in:['W'],out:['E','S'],socket:true,detail:'Every 4 beats'},delay:{name:'Delay',in:['W'],out:['E'],socket:true,detail:'Hold 2 beats'},accumulator:{name:'Accumulator',in:['W','N'],out:['E'],socket:true,detail:'Release after 3'},multi2:{name:'Multi ×2',in:['W','N'],out:['E'],socket:true,detail:'Needs 2 together'},multi3:{name:'Multi ×3',in:['W','N','S'],out:['E'],socket:true,detail:'Needs 3 together'},switcher:{name:'Switcher',in:['W'],out:['E','S'],socket:true,detail:'Alternates outputs'}};
const DIR={N:[-1,0],E:[0,1],S:[1,0],W:[0,-1]},OP={N:'S',S:'N',E:'W',W:'E'},CLOCKWISE=['N','E','S','W'];
const ACTION_DEGREES={Strike:0,Defend:0,'Twin Strike':1,Sharpen:2,Crescendo:3,Guard:0,Fortify:2,Slam:3,Brace:2,Venom:0,'Toxic Slash':1,Infect:2,Puncture:3};
export const STATUS_NAMES=['poison','strong','weak','vulnerable','dextrous','brittle','stunned'];
export function tileFor(type,turns=0){const rotate=d=>CLOCKWISE[(CLOCKWISE.indexOf(d)+turns)%4],base=TILES[type];return {...base,type,in:base.in.map(rotate),out:base.out.map(rotate)}}
export function seeded(seed){let v=seed>>>0;return()=>((v=(v*1664525+1013904223)>>>0)/4294967296)}
export function makeCard(definition,random,id,degreeRandom=random){const turns=Math.floor(random()*4),base=tileFor(definition.node,turns),incomingChance=definition.params?.incomingChance??1,inputs=definition.node==='activator'&&random()>incomingChance?[]:base.in,desired=definition.node.startsWith('multi')?base.out.length:outputCount(definition.tier,random),out=[...base.out],choices=['N','E','S','W'].filter(d=>!inputs.includes(d)&&!out.includes(d));while(out.length<desired&&choices.length){const index=Math.floor(random()*choices.length);out.push(choices.splice(index,1)[0])}const degree=MUSIC_CONFIG.useAuthoredCardDegrees?definition.degree:Math.floor(degreeRandom()*5);return {...base,in:inputs,out,id,turns,definitionId:definition.id,tier:definition.tier,degree,params:definition.params||{},shopCost:definition.shopCost,rewardWeight:definition.rewardWeight,action:definition.action?structuredClone(definition.action):{id:`${id}-connector`,name:'',text:'',kind:'connector',connector:true}}}
export const fieldCard=card=>structuredClone(card);
export function makeEncounter(seed=Math.floor(Math.random()*0xffffffff),forcedEnemy=null){const r=seeded(seed),enemy=forcedEnemy||(['striker','enemy-venom'][Math.floor(r()*2)]),pool=catalogFor(enemy);return {seed,archetype:'striker',scale:r()>.5?'major':'minor',tiles:Array.from({length:12},(_,i)=>pickCard(pool,r,`t${i}`)),enemy}}
function pickCard(pool,r,id){const total=pool.reduce((n,c)=>n+c.rewardWeight,0);let roll=r()*total,card=pool[0];for(const entry of pool){roll-=entry.rewardWeight;if(roll<=0){card=entry;break}}return makeCard(card,r,id)}
export function emptyBoard(){return Array(25).fill(null)}
export function poweredNodes(board){const powered=new Set();board.forEach((node,i)=>{if(node?.type==='activator')powered.add(i)});let changed=true;while(changed){changed=false;board.forEach((node,i)=>{if(!node||powered.has(i)||node.type==='activator')return;let inputs=0;for(const d of node.in){const [dr,dc]=DIR[d],row=Math.floor(i/5)+dr,col=i%5+dc,j=row*5+col;if(row>=0&&row<5&&col>=0&&col<5&&powered.has(j)&&board[j]?.out.includes(OP[d]))inputs++}const required=node.type.startsWith('multi')?Number(node.type.slice(-1)):1;if(inputs>=required){powered.add(i);changed=true}})}return powered}
export function reachableSocket(board){return [...poweredNodes(board)].some(i=>board[i]?.action&&!board[i].action.connector)}
function connect(board,index,d){const [dr,dc]=DIR[d],row=Math.floor(index/5)+dr,col=index%5+dc;if(row<0||row>4||col<0||col>4)return null;const next=row*5+col;return board[next]?.in?.includes(OP[d])?next:null}
function side(name,hp,board,seed,maxHp=hp){return {name,hp,maxHp,block:0,statuses:{},hpLost:0,rng:seed>>>0,board,delays:{},charges:{},incoming:{},activeNodes:[],activePulseCounts:{},misfireNodes:[],stunnedNodes:[],partialNodes:{},nodeState:{}}}
export function createBattle(playerBoard,enemyKind='striker',scale='minor',options={}){const playerMax=options.playerMaxHp||120,enemyHp=options.enemyHp||120,seed=options.seed??1,enemy=side(ARCHETYPES[enemyKind].name,enemyHp,enemyBoard(enemyKind,options.enemyPieces??3,seed^0x9e3779b9,options.enemyDepth??0,options.enemyRank,options.bossId),seed^0x9e3779b9);if(options.enemyStrength)enemy.statuses.strong=options.enemyStrength;return {beat:0,scale,over:false,player:side('Player',options.playerHp??playerMax,playerBoard,seed,playerMax),enemy,log:[]}}
const ENEMY_CELLS=[6,7,8,11,12,13,16,17,18];
function neighbor(index,d){const [dr,dc]=DIR[d],row=Math.floor(index/5)+dr,col=index%5+dc;return row<0||row>4||col<0||col>4?null:row*5+col}
function direction(from,to){return Object.keys(DIR).find(d=>neighbor(from,d)===to)}
function enemyTierLimit(depth){return depth<2?new Set(['low']):depth<4?new Set(['low','mid']):new Set(['low','mid','strong'])}
function fallbackTopology(pieces){const indexes=pieces>=7?[6,7,11,8,12,13,14,19,18,17,16]:[6,7,8,13,18];const nodes=new Map();indexes.slice(0,pieces).forEach((index,position)=>nodes.set(index,{index,parents:position?[indexes[position-1]]:[]}));if(pieces>=7){nodes.get(13).parents=[8,12];nodes.get(14).parents=[13]}return nodes}
function generatedTopology(pieces,random,needsMerge){for(let attempt=0;attempt<100;attempt++){const nodes=new Map([[ENEMY_CELLS[Math.floor(random()*ENEMY_CELLS.length)],{parents:[]}]]),children=new Map();let merged=false;while(nodes.size<pieces){const candidates=[];for(let index=0;index<25;index++){if(nodes.has(index))continue;const parents=Object.keys(DIR).map(d=>neighbor(index,d)).filter(parent=>parent!==null&&nodes.has(parent));if(parents.length)candidates.push({index,parents})}if(!candidates.length)break;const mergeCandidates=candidates.filter(candidate=>candidate.parents.length>=2);const remaining=pieces-nodes.size,chooseMerge=needsMerge&&!merged&&mergeCandidates.length&&(random()<.45||remaining<=2);const candidate=(chooseMerge?mergeCandidates:candidates)[Math.floor(random()*(chooseMerge?mergeCandidates.length:candidates.length))],parents=chooseMerge?candidate.parents.slice(0,2):[candidate.parents[Math.floor(random()*candidate.parents.length)]];nodes.set(candidate.index,{parents});for(const parent of parents)children.set(parent,[...(children.get(parent)||[]),candidate.index]);if(parents.length===2)merged=true}if(nodes.size===pieces&&(!needsMerge||merged))return nodes}return fallbackTopology(pieces)}
function enemyAllowed(def,rank='normal'){if(def.playerOnly||def.action?.modifiers?.glass)return false;if(rank==='boss')return true;if(rank==='miniboss')return def.enemyAccess!=='boss';return !def.enemyAccess||def.enemyAccess==='normal'}
function authoredBossBoard(boss){const board=emptyBoard();for(const spec of boss.board){const definition=spec.actionId?cardById(spec.actionId):null;if(spec.actionId&&(!definition||!enemyAllowed(definition,'boss')))throw new Error(`Boss ${boss.id} cannot use ${spec.actionId}`);const action=definition?.action?structuredClone(definition.action):{id:`${boss.id}-${spec.cell}-connector`,name:'',text:'',kind:'connector',connector:true};board[spec.cell]={...TILES[spec.type],type:spec.type,in:[...(spec.in||[])],out:[...(spec.out||[])],params:structuredClone(spec.params||{}),definitionId:definition?.id||`${boss.id}-${spec.cell}`,tier:definition?.tier||'connector',degree:definition?.degree||0,action}}return board}
function enemyBoard(kind,pieces=3,seed=1,depth=0,rank='normal',bossId=null){const boss=bossId?bossById(bossId):null;if(boss)return authoredBossBoard(boss);const board=emptyBoard(),random=seeded(seed),allDefs=catalogFor(kind).filter(def=>def.action&&enemyTierLimit(depth).has(def.tier)&&enemyAllowed(def,rank)),defs=depth<3?allDefs.filter(def=>def.id==='strike'):allDefs,hasMulti2=defs.some(def=>def.node==='multi2'),topology=generatedTopology(pieces,random,depth>=4&&hasMulti2),sourceIndex=[...topology.keys()][0];for(const [index,node] of topology){const children=[...topology].filter(([,other])=>other.parents.includes(index)).map(([child])=>child),isSource=index===sourceIndex,eligible=defs.filter(def=>node.parents.length===2?def.node==='multi2':!def.node.startsWith('multi')&&(def.node!=='switcher'||children.length>1)),def=eligible[Math.floor(random()*eligible.length)],type=isSource?'activator':def.node,inputs=node.parents.map(parent=>direction(index,parent)),out=children.map(child=>direction(index,child)),sourceAction={id:`enemy-source-${index}`,name:'',text:'',kind:'connector',connector:true};board[index]={...TILES[type],type,in:inputs,out,params:isSource?{cadence:4}:structuredClone(def.params||{}),definitionId:isSource?'pulse-source':def.id,tier:isSource?'connector':def.tier,degree:isSource?0:MUSIC_CONFIG.useAuthoredCardDegrees?(ACTION_DEGREES[def.action.name]??0):Math.floor(random()*5),action:isSource?sourceAction:structuredClone(def.action)}}return board}
function status(side,name){return side.statuses[name]||0}
function stateFor(side,index){return side.nodeState[index]||(side.nodeState[index]={activations:0,lastTriggeredBeat:null,lastPulseBeat:null,readyAt:0,exhausted:false,switchIndex:0})}
function mergePulse(existing,pulse){return !existing?pulse:{count:existing.count+pulse.count,generatedBeat:Math.max(existing.generatedBeat,pulse.generatedBeat)}}
function emitTo(side,index,pulse,node){if(node.type==='switcher'){const runtime=stateFor(side,index);for(let count=0;count<pulse.count;count++){const d=node.out[runtime.switchIndex%node.out.length],j=connect(side.board,index,d);if(j!==null)side.nextIncoming[j]=mergePulse(side.nextIncoming[j],{...pulse,count:1});runtime.switchIndex=(runtime.switchIndex+1)%node.out.length}return}for(const d of node.out){const j=connect(side.board,index,d);if(j!==null)side.nextIncoming[j]=mergePulse(side.nextIncoming[j],pulse)}}
function amount(spec,ctx){if(typeof spec==='number')return spec;const source=spec?.from;const values={pulseAge:ctx.beat-ctx.pulse.generatedBeat,beatsSinceTriggered:ctx.state.lastTriggeredBeat===null?ctx.beat:ctx.beat-ctx.state.lastTriggeredBeat,beatsSincePulsed:ctx.state.lastPulseBeat===null?ctx.beat:ctx.beat-ctx.state.lastPulseBeat,activationCount:ctx.state.activations,selfMissingHp:ctx.side.maxHp-ctx.side.hp,enemyMissingHp:ctx.other.maxHp-ctx.other.hp,enemyCurrentHp:ctx.other.hp,selfHpLost:ctx.side.hpLost,enemyHpLost:ctx.other.hpLost,selfBlock:ctx.side.block,connectedNeighbors:neighborCount(ctx.side.board,ctx.index,true),unconnectedNeighbors:neighborCount(ctx.side.board,ctx.index,false),matchingBoardActions:matchingActions(ctx.side.board,ctx.index)};return Math.max(0,((spec?.base||0)+(source?(values[source]||0)*(spec.per??1):0))*(ctx.multiplier||1))}
function neighborCount(board,index,wantConnected){let count=0;for(const d of Object.keys(DIR)){const [dr,dc]=DIR[d],row=Math.floor(index/5)+dr,col=index%5+dc,j=row*5+col;if(row<0||row>4||col<0||col>4||!board[j])continue;const connected=board[index].out.includes(d)&&board[j].in.includes(OP[d])||board[index].in.includes(d)&&board[j].out.includes(OP[d]);if(connected===wantConnected)count++}return count}
function matchingActions(board,index){const action=board[index]?.action?.name;return board.reduce((count,node,i)=>count+(i!==index&&node?.action?.name===action?1:0),0)}
function damage(source,target,n,events,label,strongMultiplier=1,usesCombatModifiers=true,ignoresBlock=false){const raw=usesCombatModifiers?Math.max(0,n+status(source,'strong')*strongMultiplier-status(source,'weak')):Math.max(0,n),total=usesCombatModifiers?raw+status(target,'vulnerable'):raw,absorbed=ignoresBlock?0:Math.min(target.block,total),lost=total-absorbed;target.block-=absorbed;target.hp-=lost;target.hpLost+=lost;events.push(`${source.name}: ${label} deals ${lost}${absorbed?` (${absorbed} blocked)`:''}.`);if(lost)reactToDamage(target,source,lost,events)}
function reactToDamage(side,other,lost,events){side.board.forEach((node,index)=>{if(!node?.action?.reactive)return;const ctx={side,other,index,beat:side._beat,pulse:{count:1,generatedBeat:side._beat},state:stateFor(side,index)};for(const entry of node.action.reactive.filter(x=>x.trigger==='damageTaken'))executeEffect(entry,ctx,events)})}
function executeEffect(entry,ctx,events){if(entry.when?.type==='allBoardTag'&&!ctx.side.board.filter(Boolean).every(node=>node.action?.tags?.includes(entry.when.tag)))return;if(entry.when?.type==='enemyHpAtMost'&&ctx.other.hp>ctx.other.maxHp*entry.when.fraction)return;const target=entry.target==='enemy'?ctx.other:ctx.side,value=amount(entry.value,ctx);if(entry.type==='damage'){if(entry.spend==='selfBlock')ctx.side.block=0;for(let i=0;i<(entry.times||1);i++)damage(ctx.side,target,value,events,ctx.side.board[ctx.index].action.name,entry.strongMultiplier||1)}else if(entry.type==='block'){const gained=Math.max(0,value+status(ctx.side,'dextrous')-status(ctx.side,'brittle'));ctx.side.block+=gained;events.push(`${ctx.side.name}: gains ${gained} block.`)}else if(entry.type==='status'){target.statuses[entry.status]=(target.statuses[entry.status]||0)+value;events.push(`${ctx.side.name}: applies ${value} ${entry.status}.`)}else if(entry.type==='charge'){const node=ctx.side.board[ctx.index],charge=ctx.side.charges[ctx.index]||{count:0,generatedBeat:ctx.beat};charge.count+=value;ctx.side.charges[ctx.index]=charge;const threshold=node?.params?.threshold||3;if(charge.count>=threshold){charge.count-=threshold;activate(ctx.side,ctx.other,ctx.index,events,{count:1,generatedBeat:ctx.beat})}events.push(`${ctx.side.name}: ${node?.action?.name||'Node'} gains ${value} charge.`)}}
function roll(side){side.rng=(Math.imul(side.rng,1664525)+1013904223)>>>0;return side.rng/4294967296}
function activate(side,other,index,events,pulse,ambient=false){const node=side.board[index];if(!node)return;const runtime=stateFor(side,index),pass=()=>emitTo(side,index,pulse,node),isMulti=node.type.startsWith('multi'),resolutions=isMulti?1:pulse.count;side.activeNodes.push(index);side.activePulseCounts[index]=(side.activePulseCounts[index]||0)+pulse.count;if(ambient||runtime.exhausted||!node.action||node.action.connector){runtime.lastPulseBeat=side._beat;events.push(`${side.name}: ${node.name} relays${pulse.count>1?` ×${pulse.count}`:''}.`);pass();return}const rules=node.action.rules||{},glass=node.action.modifiers?.glass;let activations=0;for(let count=0;count<resolutions;count++){if(runtime.exhausted)continue;if(glass&&roll(side)<=(glass.chance??.05)){side.board[index]=null;events.push(`${side.name}: ${node.action.name} shatters.`);return}if(status(side,'stunned')){side.statuses.stunned--;side.stunnedNodes.push(index);runtime.lastPulseBeat=side._beat;events.push(`${side.name}: ${node.action.name} is stunned.`);continue}if(runtime.readyAt>side._beat){side.misfireNodes.push(index);runtime.lastPulseBeat=side._beat;events.push(`${side.name}: ${node.action.name} misfires on cooldown.`);for(const entry of rules.onCooldown||[])executeEffect(entry,{side,other,index,beat:side._beat,pulse:{...pulse,count:1},state:runtime},events);continue}runtime.activations++;activations++;const ctx={side,other,index,beat:side._beat,pulse:{...pulse,count:1},state:runtime,multiplier:glass?.multiplier||1};for(const entry of node.action.effects||[])executeEffect(entry,ctx,events);runtime.lastTriggeredBeat=runtime.lastPulseBeat=side._beat;if(rules.cooldown)runtime.readyAt=side._beat+rules.cooldown;if(rules.exhaust&&runtime.activations>=rules.exhaust){runtime.exhausted=true;events.push(`${side.name}: ${node.action.name} exhausts.`)}}if(activations)events.push(`${side.name}: ${node.name} activates${isMulti?` (SYNC ×${pulse.count})`:activations>1?` ×${activations}`:''} → ${node.action.name}.`);pass()}
function process(side,other,events,ambient){const emitted=[];for(let i=0;i<25;i++){const n=side.board[i];if(!n)continue;if(n.type==='activator'&&side._beat%(n.params?.cadence||4)===1)emitted.push([i,{count:1,generatedBeat:side._beat}]);const delay=side.delays[i];if(delay?.due===side._beat){delete side.delays[i];emitted.push([i,delay.pulse])}}for(const [key,pulse] of Object.entries(side.incoming)){const i=+key,n=side.board[i];if(!n)continue;if(n.type==='delay'){side.delays[i]={due:side._beat+(n.params?.beats||2),pulse};events.push(`${side.name}: Delay holds a pulse.`)}else if(n.type==='accumulator'){const charge=side.charges[i]||{count:0,generatedBeat:pulse.generatedBeat};charge.count+=pulse.count;charge.generatedBeat=Math.max(charge.generatedBeat,pulse.generatedBeat);side.charges[i]=charge;if(charge.count>=(n.params?.threshold||3)){charge.count-=n.params?.threshold||3;emitted.push([i,{count:1,generatedBeat:charge.generatedBeat}])}}else if(n.type.startsWith('multi')){const required=Number(n.type.slice(-1));if(pulse.count>=required)emitted.push([i,pulse]);else{side.partialNodes[i]=pulse.count/required;events.push(`${side.name}: ${n.name} receives ${pulse.count}/${required} pulses.`)}}else emitted.push([i,pulse])}side.incoming={};for(const [i,pulse] of emitted)activate(side,other,i,events,pulse,ambient)}
function tickStatuses(side,other,events){const poison=status(side,'poison');if(poison)damage(other,side,poison,events,'Poison',1,false,true);for(const name of STATUS_NAMES)if(side.statuses[name]){side.statuses[name]--;if(side.statuses[name]<=0)delete side.statuses[name]}}
function battleFatigue(side,events){side.hp--;side.hpLost++;events.push(`${side.name}: Battle fatigue deals 1 unblockable damage.`)}
export function advance(state){const s=structuredClone(state),events=[],ambient=s.over;s.beat++;s.player._beat=s.enemy._beat=s.beat;s.player.activeNodes=[];s.enemy.activeNodes=[];s.player.activePulseCounts={};s.enemy.activePulseCounts={};s.player.misfireNodes=[];s.enemy.misfireNodes=[];s.player.stunnedNodes=[];s.enemy.stunnedNodes=[];s.player.partialNodes={};s.enemy.partialNodes={};s.player.nextIncoming={};s.enemy.nextIncoming={};process(s.player,s.enemy,events,ambient);process(s.enemy,s.player,events,ambient);s.player.incoming=s.player.nextIncoming;s.enemy.incoming=s.enemy.nextIncoming;if(!ambient){tickStatuses(s.player,s.enemy,events);tickStatuses(s.enemy,s.player,events);if(s.beat>100){battleFatigue(s.player,events);battleFatigue(s.enemy,events)}s.player.hp=Math.max(0,s.player.hp);s.enemy.hp=Math.max(0,s.enemy.hp);s.log=[...s.log,...events];if(!s.player.hp||!s.enemy.hp){s.over=true;s.result=s.player.hp===s.enemy.hp?'Draw':s.player.hp?'Victory':'Defeat'}}delete s.player.nextIncoming;delete s.enemy.nextIncoming;return {...s,events}}
